// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabajo_grupal.Data;

#nullable disable

namespace Trabajo_grupal.Migrations
{
    [DbContext(typeof(Trabajo_grupalContext))]
    [Migration("20240416031412_CambiosBdd")]
    partial class CambiosBdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trabajo_grupal.Models.Estudiante", b =>
                {
                    b.Property<int>("IdBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBanner"));

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVacunacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recintoDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("vacunaid")
                        .HasColumnType("int");

                    b.HasKey("IdBanner");

                    b.HasIndex("recintoDireccion");

                    b.HasIndex("vacunaid");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("Trabajo_grupal.Models.Recinto_Vacuanción", b =>
                {
                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Direccion");

                    b.ToTable("Recinto_Vacuanción");
                });

            modelBuilder.Entity("Trabajo_grupal.Models.Vacuna", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Vacuna");
                });

            modelBuilder.Entity("Trabajo_grupal.Models.Estudiante", b =>
                {
                    b.HasOne("Trabajo_grupal.Models.Recinto_Vacuanción", "recinto")
                        .WithMany()
                        .HasForeignKey("recintoDireccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trabajo_grupal.Models.Vacuna", "vacuna")
                        .WithMany()
                        .HasForeignKey("vacunaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recinto");

                    b.Navigation("vacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
